import "./globals.css";
import { ReactNode } from "react";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import LogoutButton from "@/components/LogoutButton";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: ReactNode }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en" className="h-full">
      <body className="m-0 min-h-screen flex flex-col antialiased">
        <header className="w-full bg-white px-6 py-4 flex justify-end items-center shadow">
          {session?.user ? (
            <div className="flex items-center gap-4">
              <span className="text-sm text-gray-700">Hello, {session.user.email}</span>
              <LogoutButton />
            </div>
          ) : (
            <span className="text-sm text-gray-500">Not logged in</span>
          )}
        </header>
        <main className="flex-1 p-0 m-0">{children}</main>
      </body>
    </html>
  );
}
